version: '3.7'

services:
  server1:
    container_name: server1
    build: .
    environment:
      - PORT=3001
      - NAME=server1.2
      - REDIS_URL=redis://redis:6379
    ports:
      - "3001:3001"
    depends_on:
      - redis
    networks:
      - redis-net

  server2:
    container_name: server2
    build: .
    environment:
      - PORT=3002
      - NAME=server2.2
      - REDIS_URL=redis://redis:6379
    ports:
      - "3002:3002"
    depends_on:
      - redis
    networks:
      - redis-net

  server3:
    container_name: server3
    build: .
    environment:
      - PORT=3003
      - NAME=server3.2
      - REDIS_URL=redis://redis:6379
    ports:
      - "3003:3003"
    depends_on:
      - redis
    networks:
      - redis-net

  kotlin-service:
    image: kotlin-load_balancer
    ports:
      - "8080:8080"
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - redis-net
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5" # Half a CPU core
        reservations:
          memory: 256M
          cpus: "0.25" # A quarter of a CPU core

  rust-service:
    image: rust-load_balancer
    ports:
      - "8081:8081"
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - redis-net
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5" # Half a CPU core
        reservations:
          memory: 256M
          cpus: "0.25" # A quarter of a CPU core

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis-net
    command: ["redis-server", "--appendonly", "yes"]

networks:
  redis-net:
    driver: bridge
